# 应用名称
spring:
  application:
    name: studentserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/xk?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: 123456
# 应用服务 WEB 访问端口
server:
  port: 7004
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
#指定Mybatis的实体目录
  type-aliases-package: com.example.studentserver.mybatis.entity
# 数据库驱动：
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

security:
  oauth2:
    client:
      client-id: client_2
      client-secret: 123456
    resource:
      token-info-uri: http://127.0.0.1:7011/oauth/check_token



