# 应用名称
spring:
  application:
    name: consumer
# 应用服务 WEB 访问端口
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
